### ISSUE TITLE
ESP not working...

### ISSUE THREAD

**Issue by limquanly** [kenn-notation/ValorantCheatExternal#5]
Hi can anyone help me.
i am using windows 10 21h1 but using DirectX 12 ( do i need to downgrade to 10? )
Extracted the files into a new file at my desktop or do i need to extract to valorant file if yes can anyone tell me the specific place Please 
I did all the steps and open valorant the menu came up but only esp is not working.
Anyone willing to help.?
Quanly#1306

**Comment by isvktt** [comment]
you need driver, my discord : $bk#7529
